# Configuration file for NetworkManager.
# See "man 5 NetworkManager.conf" for details.

# [main]
# plugins=keyfile
# dhcp=internal
# dns=systemd-resolved

[device:virbr]
match-device=interface-name:virbr-*
managed=0

[device:incbr]
match-device=interface-name:incbr-*
managed=0

[device:docker]
match-device=interface-name:docker*
managed=0

[device:podman]
match-device=interface-name:podman*
managed=0

[device:tailscale]
match-device=interface-name:tailscale*
managed=0

[device:wg]
match-device=interface-name:wg-*
managed=0

[device:wifi]
match-device=type:wifi
wifi.backend=iwd
