# vim: ft=toml:

[storage]

# Default storage driver, must be set for proper operation.
driver = ""

# Priority list for the storage drivers that will be tested one
# after the other to pick the storage driver if it is not defined.
driver_priority = [
  "btrfs",
  "zfs",
  "overlay",
  "vfs",
]

# Primary Read/Write location of container storage
# When changing the graphroot location on an SELinux system, you must
# ensure the labeling matches the default location's labels with the
# following commands:
# semanage fcontext -a -e /var/lib/containers/storage /NEWSTORAGEPATH
# restorecon -R -v /NEWSTORAGEPATH
graphroot = "/var/lib/containers/storage"

# Optional alternate location of image store if a location separate from the
# container store is required. If set, it must be different than graphroot.
imagestore = "/var/lib/containers/images"

# Storage path for rootless users
rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options.overlay]

# Set to skip a PRIVATE bind mount on the storage home directory.
# This is a "string bool": "false" | "true" (cannot be native TOML boolean)
# skip_mount_home = "true"
