## These examples include common files that users may wish to include.
##
## Please be careful with what you whitelist here -- `pacman -Syu` may touch
## these files and thus prevent atomic updates from adjusting them in the future.
##
## "/usr/lib/rauc/atomic-update-keep.conf" contains the list of files
## that are already preserved by default.
##
## The wildcard '*' will match every character, except forward slashes.
## The wildcard '**' is like '*', but it will include forward slashes.

## Keep changes to systemd config
# /etc/systemd/*.conf

## Keep drop-in changes for mkinitcpio
# /etc/mkinitcpio.conf.d/*.conf

## Keep all edits to any files.
## DANGEROUS! Any files you (or pacman) touch in /etc will forever shadow all
## upstream changes from future atomic updates, leading to hard to diagnose
## breakage. You get to keep the pieces.
# /etc/**

/etc/fstab
/etc/resolv.conf

/etc/admin/**

/etc/systemd/*.conf.d/9*.conf
/etc/systemd/system/*.d/override.conf
/etc/NetworkManager/conf.d/9*.conf

/etc/sysctl.d/9*.conf
/etc/sudoers.d/9*
/etc/ssh/*.d/1*.conf
/etc/pam.d/system-auth
/etc/pam.d/sudo
/etc/modprobe.d/9*.conf
/etc/ssh/*_key*

/etc/shadowsocks-rust/*.json
/etc/firewalld/**
/etc/jellyfin/**
/etc/nginx/**

/usr/local/bin/*
